"""Structured vision provider API."""

from .base import (
    AIError,
    AIOutputError,
    AIPaymentRequiredError,
    AITransientError,
    AIUsage,
    BilingualDescriptions,
    BudgetExceededError,
    ContentClassification,
    CostEstimate,
    DescriptionBatch,
    DescriptionItem,
    DescriptionRequest,
    DescriptionResult,
    LocalizedDescription,
    ProviderCapabilities,
    RequestBudget,
    SemanticFacets,
    SemanticMediaReference,
    SemanticTextContent,
    SemanticTextItem,
    UnknownCostError,
    VisionContext,
    VisionImage,
    VisionProvider,
    describe_with_recovery,
    validate_result_labels,
)
from .gemini import GeminiVisionProvider, ModelPricing
from .openai import OpenAIVisionProvider
from .registry import ProviderRegistry, default_registry

__all__ = [
    "AIError",
    "AIOutputError",
    "AIPaymentRequiredError",
    "AITransientError",
    "AIUsage",
    "BilingualDescriptions",
    "BudgetExceededError",
    "ContentClassification",
    "CostEstimate",
    "DescriptionBatch",
    "DescriptionItem",
    "DescriptionRequest",
    "DescriptionResult",
    "GeminiVisionProvider",
    "LocalizedDescription",
    "ModelPricing",
    "OpenAIVisionProvider",
    "ProviderCapabilities",
    "ProviderRegistry",
    "RequestBudget",
    "SemanticFacets",
    "SemanticMediaReference",
    "SemanticTextContent",
    "SemanticTextItem",
    "UnknownCostError",
    "VisionContext",
    "VisionImage",
    "VisionProvider",
    "default_registry",
    "describe_with_recovery",
    "validate_result_labels",
]
